# Generated by Django 4.2.4 on 2023-08-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_profile_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AlterField(
            model_name='profile',
            name='attainable_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dslam_hostname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frame',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pop_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speed',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
